### ISSUE TITLE
Object.keys called on non-object

### ISSUE THREAD

**Issue by s3u** [mikeal/replicate#4]
Hi - I npm installed replicated. replicate failed with the following error.

~> replicate http://isaacs.iriscouch.com/registry http://user:pwd@localhost:8000

/usr/local/lib/node_modules/replicate/main.js:136
        if (Object.keys(body).length === 0) cb({})
                   ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at Request.callback (/usr/local/lib/node_modules/replicate/main.js:136:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/replicate/node_modules/request/main.js:314:21)
    at Request.emit (events.js:64:17)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/replicate/node_modules/request/main.js:295:19)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at Socket.ondata (http.js:1231:22)
    at Socket._onReadable (net.js:683:27)
    at IOWatcher.onReadable [as callback](net.js:177:10)

On couch side, I see the following info logs.

[info] [<0.6666.3>] 127.0.0.1 - - 'GET' / 200
[info] [<0.6672.3>] 127.0.0.1 - - 'POST' /_missing_revs 400

**Comment by max-mapper** [comment]
what version of couchdb are you running? 

additionally,

if you add `console.log(body)` to the callback on line `115` what does it say? it should be the error message from the `400` error in your couch logs

**Comment by s3u** [comment]
Couch 1.1.0

The body is

{ error: 'illegal_database_name',
  reason: 'Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed. Must begin with a letter.' }

**Comment by s3u** [comment]
Please ignore. This is a false alarm.

I forgot to add the "/registry" at the end, which caused replicate to use 

http://localhost:8000/_missing_revs

with a POST. It is working now.

Sorry for wasting your time.

**Comment by max-mapper** [comment]
@s3u its okay, now I know I should add a verbose mode. thanks for the bug report
